version: "3.9"

services:
  keycloak_db:
    container_name: keycloak_db
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_USER=kc_user
      - MYSQL_PASSWORD=kc_password
      - MYSQL_ROOT_PASSWORD=keycloak
      - MYSQL_DATABASE=keycloak
    ports:
      - "3306:3306"
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak_sys:
    container_name: keycloak_sys
    image: jboss/keycloak:16.1.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin_user
      - KEYCLOAK_PASSWORD=admin_password
      - DB_VENDOR=mysql
      - DB_ADDR=keycloak_db
      - DB_PORT=3306
      - DB_USER=kc_user
      - DB_PASSWORD=kc_password
      - DB_DATABASE=keycloak
    depends_on:
      - keycloak_db
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume: