version: "3.9"

services:
  keycloak_db:
    container_name: keycloak_db
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_USER=kc_user
      - MYSQL_PASSWORD=kc_password
      - MYSQL_ROOT_PASSWORD=keycloak
      - MYSQL_DATABASE=keycloak
    ports:
      - "3306:3306"
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak_sys:
    container_name: keycloak_sys
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      - KC_DB=mysql
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL_HOST=keycloak_db
      - KC_DB_URL_PORT=3306
      - KC_DB_SCHEMA=keycloak
      - KC_HOSTNAME=localhost
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
    ports:
      - "8180:8080"
    depends_on:
      - keycloak_db
    networks:
      - keycloak-and-mysql-network

#  keycloak_sys:
#    container_name: keycloak_sys
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - keycloak_db
#    networks:
#      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume: